spring:
  config.activate.on-profile: default
  sql.init.platform: h2
  web.resources.static-locations: file:./app/
cds:
  data-source.auto-config.enabled: false
  security:
    mock.users:
      alice:
        roles: [ admin, support ]
      bob:
        roles: [ support ]
---
management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults:
      enabled: false
    ping:
      enabled: true
    db:
      enabled: true
